[colors.bright]
black = "#565f89"
blue = "#41a6b5"
cyan = "#1abc9c"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.cursor]
cursor = "#c0caf5"
text = "#24283b"

[colors.normal]
black = "#24283b"
blue = "#41a6b5"
cyan = "#1abc9c"
green = "#9ece6a"
magenta = "#bb9af7"
red = "#f7768e"
white = "#c0caf5"
yellow = "#e0af68"

[colors.primary]
background = "#24283b"
bright_foreground = "#c0caf5"
foreground = "#c0caf5"

[colors.selection]
background = "#292e42"
text = "#c0caf5"

[font]
size = 12
[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"

[window]
opacity = 1.0
