#!/usr/bin/env zsh

if [ -f "$HOME/.config/zsh/environment_overrides.zsh" ]; then
    source "$HOME/.config/zsh/environment_overrides.zsh"
fi

export LANG=en_US.UTF-8
export LC_ALL="C.UTF-8"
export PATH=$HOME/.local/bin:$PATH


if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && [ "${PROMPT_APP}" = "p10k" ];  then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if command -v tmux>/dev/null; then
	if [ "$DISABLE_TMUX" = "true" ]; then
		echo "TMUX is disabled through the environment"
	else
        if [ "$EUID" -eq 0 ]; then
            echo "TMUX is disabled for root"
        else
            if [[ -z "$TMUX" ]]; then
                if [[ "$TERM_PROGRAM" != "vscode" ]]; then
                    if [ `tmux ls 2>&1 | wc -l` -gt 1 ]; then
                        tmux choose-session
                        tmux attach
                    else
                        tmux new-session -A -s main
                    fi
                fi
            fi
        fi
    fi
else 
	echo "tmux not installed. Run ./deploy to configure dependencies"
fi

# Activate zoxide shell integration if it is installed
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi

# Enable shell integration for fzf (completion and bindings)
if command -v fzf &> /dev/null; then
  source <(fzf --zsh)
fi

source ${ZDOTDIR}/base_config.sh
source ${ZDOTDIR}/syntax.sh
source ${ZDOTDIR}/aliases.sh
source ${ZDOTDIR}/custom-functions.sh
source ${ZDOTDIR}/zsh-autosuggestions.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#999'

# Enables improved vim motions
source ${ZDOTDIR}/zsh-vi-mode/zsh-vi-mode.plugin.zsh


function yz() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}



case "${PROMPT_APP}" in
    "starship")
        export STARSHIP_CONFIG=~/.config/starship/starship.toml
        eval "$(starship init zsh)"
        ;;
    "p10k")
        source ${HOME}/.local/share/themes/static/powerlevel10k/powerlevel10k.zsh-theme
        [[ ! -f ${ZDOTDIR}/p10k.zsh ]] || source ${ZDOTDIR}/p10k.zsh
        ;;
    "oh-my-posh")
        eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/config.yaml)"
        ;;
esac
