# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family       JetBrainsMono Nerd Font Mono
bold_font         JetBrainsMono Nerd Font Mono
italic_font       JetBrainsMono Nerd Font Mono
bold_italic_font  JetBrainsMono Nerd Font Mono


font_size 12.0


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME%

[window]
confirm_os_window_close 0
