# First check if tmux is installed
# Next check if tmux is not disabled
# Next check that we are not sourcing .zshrc as part of tmux initialization
# Last check that we are not a vscode terminal
# Otherwise attach to existing tmux session

# Extend the path with some optional local binary directories. These take precedence over the rest of the path

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.local/sbin" ] ; then
    PATH="$HOME/.local/sbin:$PATH"
fi

if [ -d "$HOME/opt/bin" ] ; then
    PATH="$HOME/opt/bin:$PATH"
fi

# export DISABLE_TMUX=true
export LANG=en_US.UTF-8
export LC_ALL="C.UTF-8"

export DOTFILES=${$(readlink "${(%):-%x}"):h:h} # This command detirmines the location of the dotfiles directory

source ${DOTFILES}/powerlevel10k/powerlevel10k.zsh-theme

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ${DOTFILES}/zsh/p10k.zsh ]] || source ${DOTFILES}/zsh/p10k.zsh


if command -v tmux>/dev/null; then
	if [ "$DISABLE_TMUX" = "true" ]; then
		echo "TMUX is disabled through the environment"
	else
        if [ "$EUID" -eq 0 ]; then
            echo "TMUX is disabled for root"
        else
            if [[ -z "$TMUX" ]]; then
                if [[ "$TERM_PROGRAM" != "vscode" ]]; then
                    if [ `tmux ls 2>&1 | wc -l` -gt 1 ]; then
                        tmux choose-session
                        tmux attach
                    else
                        tmux new-session -A -s main
                    fi
                fi
            fi
        fi
    fi
else 
	echo "tmux not installed. Run ./deploy to configure dependencies"
fi

# Activate zoxide shell integration if it is installed
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi

# Enable shell integration for fzf (completion and bindings)
if command -v fzf &> /dev/null; then
  source <(fzf --zsh)
fi

source ${DOTFILES}/zsh/base_config.sh
source ${DOTFILES}/zsh/syntax.sh
source ${DOTFILES}/zsh/aliases.sh

source ${DOTFILES}/zsh/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#999'

# Set bat as the manpager when it is installed
if type "bat" > /dev/null; then
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# Modification to include sbin directories

export PATH=$PATH:/sbin/:/usr/sbin:$HOME/.local/share/tmux/plugins/tmuxifier/bin
eval "$(tmuxifier init -)"


#source ~/dotfiles/zsh/utils/zsh-vi-mode.plugin.zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval $(ssh-agent -s)
  ssh-add
fi

function yz() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
