# First check if tmux is installed
# Next check if tmux is not disabled
# Next check that we are not sourcing .zshrc as part of tmux initialization
# Last check that we are not a vscode terminal
# Otherwise attach to existing tmux session

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# export DISABLE_TMUX=true
export LANG=en_US.UTF-8
export LC_ALL="C.UTF-8"

export DOTFILES=~/dotfiles

source ~/dotfiles/powerlevel10k/powerlevel10k.zsh-theme

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/dotfiles/zsh/p10k.zsh ]] || source ~/dotfiles/zsh/p10k.zsh
#source '/home/user/dotfiles/zsh/zshrc_manager.sh'



if command -v tmux>/dev/null; then
	if [ "$DISABLE_TMUX" = "true" ]; then
		echo "TMUX is disabled through the environment"
	else
        if [ "$EUID" -eq 0 ]; then
            echo "TMUX is disabled for root"
        else
            if [[ -z "$TMUX" ]]; then
                if [[ "$TERM_PROGRAM" != "vscode" ]]; then
                    if [ `tmux ls 2>&1 | wc -l` -gt 1 ]; then
                        tmux choose-session
                        tmux attach
                    else
                        tmux new-session -A -s main
                    fi
                fi
            fi
        fi
    fi
else 
	echo "tmux not installed. Run ./deploy to configure dependencies"
fi

source ~/dotfiles/zsh/zshrc.sh
source ~/dotfiles/zsh/syntax.sh
source ~/dotfiles/zsh/autosuggestions.sh
source ~/dotfiles/zsh/prompt.sh
source ~/dotfiles/zsh/aliases.sh

# Added for support of zoxide

export PATH=$PATH:'~/.local/bin/'

# Set bat as the manpager when it is installed
if type "bat" > /dev/null; then
  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi
eval "$(zoxide init --cmd cd zsh)"

# Modification to include sbin directories

export PATH=$PATH:/sbin/:/usr/sbin:'~/.local/sbin/'

#source ~/dotfiles/zsh/utils/zsh-vi-mode.plugin.zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
